### ISSUE TITLE
 tagai doesn't build on openSuse 12.1

### ISSUE THREAD

**Issue by lanigb** [Gnurou/tagainijisho#53]
/usr/lib/gcc/i586-suse-linux/4.6/../../../../i586-suse-linux/bin/ld: ../../sqlite/libtagaini_sqlite.a(sqlite3.c.o): undefined reference to symbol 'pthread_mutex_trylock@@GLIBC_2.0'
/usr/lib/gcc/i586-suse-linux/4.6/../../../../i586-suse-linux/bin/ld: note: 'pthread_mutex_trylock@@GLIBC_2.0' is defined in DSO /lib/libpthread.so.0 so try adding it to the linker command line
/lib/libpthread.so.0: could not read symbols: Invalid operation
collect2: ld returned 1 exit status

It seems it fails too on opensuse openbuild system.

Best regards,
